spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest-jdbc-boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
   # properties:
     # hibernate:
      #  dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
      